apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test-deployment
  labels:
    app: docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker-test
        image: 03322504719/docker-test
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  selector:
    app: docker-test-deployment
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer